# Generated by Django 5.2 on 2025-05-11 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_subject_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=255)),
                ('files_count', models.IntegerField()),
                ('review_params', models.CharField(blank=True, max_length=255)),
                ('time_update', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=20)),
                ('changer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.teacher')),
            ],
            options={
                'ordering': ['-time_update'],
            },
        ),
    ]
